version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - cd ers/ui
      - npm install
  build:
    commands:
      -npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'ers-ui/build'